### ISSUE TITLE
Reason for the .NET Standard 2.0 retarget.

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [ijat/ReedSolomonCore#1]
Why is the Nuget package targeted .NET Standard **2.0** if the original repo targeted .NET Standard **1.0**?

By re-targeting the package from  .NET Standard 1.0 to 2.0, you target **less** .NET versions, this means the number of potential users of the package will be less as well.

On Microsoft Docs is a [page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) about .NET Standard, on [dotnet.microsoft.com](https://dotnet.microsoft.com/platform/dotnet-standard) is a better visualization of implemented .NET Standard versions.

**Comment by ijat** [comment]
Actually i try to open original repo in VS19 but it was hassle to convert xproj to csproj. So i just create a default library and paste all src files there. No specific reason for me to target Net Standard 2.0, it was the default settings which I'm not bother to change it. Feel free to use original repo if this doesn't suit your project.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
It was just a simple question, [I published my own Reed-Solomon library as a NuGet package](https://www.nuget.org/packages/STH1123.ReedSolomon/) about a month ago, so, I don't need this one.
